### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by kemcake**
Hi there 🙌 

I had some issues using this component.
This PR fix: 
- Height 0 not working on Android
- Render custom active divider
- Custom sortRowStyle props
- Support scrollView with margin (navbar/tabbar/etc.)
- Use onContentSizeChanged instead on onScroll
- Fix scrollTo after release
- Allow to disable scroll

Let's discuss about all these improvements

### CODE REVIEW

**Comment by deanmcpherson** [comment]
Hey @kemcake, looks great. I'll test it out to make sure it's all working correctly, and will get back to / merge if all is good.

**Comment by deanmcpherson** [comment]
Merged, your changes are in the 0.0.8 release on npm.

**Comment by kemcake** [comment]
👍

**Comment by ahanriat** [comment]
🎉

**Comment by antoinerousseau** [comment]
This broke my page:

gif

**Comment by kemcake** [comment]
@antoinerousseau don't really see what's wrong, you're talking about the scroll after a drop ?

**Comment by antoinerousseau** [comment]
@kemcake  the card above the one moved moves below before starting any movement

**Pull request merged**
