### PR TITLE
Refactor & Bug fix

### PR DESCRIPTION
**Pull request by nihgwu**

### CODE REVIEW

**Comment by nihgwu** [comment]
Yes, I'm using `react-navigation`, and the screen contains `SortableListView` will be animate `translateY` to get to front( a custom `Modal` not using the provided `Modal` by React Native), then the measure will be wrong, I've read the doc, it says that measure will give the wrong value when animating, the right way it to get the value via `onLayout` or measure after animation, so I chose the second solution, measure the layout `afterInteraction`

**Comment by nihgwu** [comment]
@chetstone I'm sure this change is safe, I've test it in my own app. I've been using this components for a year, it's doing really a good job, but I find that bug after I switch from `Modal` to a custom `View`, so I try to resolve this, the main changes in this PR are:
1. codemod(es5 -> es6)
2. eslint --fix
3. prettier
4. bug fix for animating view
5. clean up

The main reason for me to change the code style is that ES5 is really out of fashion in React Native development nowadays, gives several warnings, and the old code style is not friend enough for other contributors, there a still some unless code there, but I think this is the first step forward, I'll continue to polish this code base

**Comment by chetstone** [comment]
@nihgwu Thanks very much for your contribution and your offer to continue polishing. That's great!. And thanks for educating us about some  of these tools. `prettier` looks like a great tool for new code and possibly for restyling old code if the project has a robust regression test suite. Unfortunately we don't have that --- we just have one minimal jest test and the example app that has to be run manually. (I assume you have at least tested with those).

I agree that it's good to keep up to date, but at a minimum, I will want to read the code carefully and try it with my app, and I won't have time to do that for a few weeks. In the meantime, the following will help:

1. Perhaps some other people could try this PR in their code and report here whether or not they found any regressions.
2. Any possibility you could split this into 2 PR's? One with just the bug fix and another with all the styling changes?

Finally, in a quick glance at the diffs, I already discovered one problem. Since ES6 doesn't support mixins, you have removed `react-timer-mixin`. How do you clean up timers when the component unmounts?

**Comment by nihgwu** [comment]
There is no setTimeout any more, I will clean the dependencies

On 16 May 2017, at 02:01, Chester Wood <notifications@github.com<mailto:notifications@github.com>> wrote:


@nihgwu<https://github.com/nihgwu> Thanks very much for your contribution and your offer to continue polishing. That's great!. And thanks for educating us about some of these tools. prettier looks like a great tool for new code and possibly for restyling old code if the project has a robust regression test suite. Unfortunately we don't have that --- we just have one minimal jest test and the example app that has to be run manually. (I assume you have at least tested with those).

I agree that it's good to keep up to date, but at a minimum, I will want to read the code carefully and try it with my app, and I won't have time to do that for a few weeks. In the meantime, the following will help:

  1.  Perhaps some other people could try this PR in their code and report here whether or not they found any regressions.
  2.  Any possibility you could split this into 2 PR's? One with just the bug fix and another with all the styling changes?

Finally, in a quick glance at the diffs, I already discovered one problem. Since ES6 doesn't support mixins, you have removed react-timer-mixin. How do you clean up timers when the component unmounts?

**Comment by nihgwu** [comment]
@chetstone mind to step forward to merge this? I didn't change any original logic code

**Comment by nihgwu** [comment]
I've been using this version in my app for weeks and it works as before

**Comment by chetstone** [comment]
@nihgwu I'll try to get time to look at this soon.

**Comment by chetstone** [comment]
@nihgwu I took a look at the changes, and the cleanup/prettier/es6 changes look straightforward and a good idea. Some of your other changes I don't quite understand, but the main problem is that the tests included in the repository don't work for me. 

`npm run test` fails with
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `MyComponent`.
```
And the test app in the Sortable directory fails the same way. Evidently the way you've exported the component only works with the es6 `import` method, because if I change
```
let SortableListView = require('react-native-sortable-listview');
```
to
```
import SortableListView from 'react-native-sortable-listview'
```
that problem goes away. Please fix the export so the component is backwards compatible -- it should work with either `import` or `require`.

Then once that problem is out of the way, the Sortable app still has major problems. When you pick up a row to move it, the 'shadow' jumps to the top of the list and does not track the slot it is to be dropped in. And it's impossible to move it where you want it.

Please take a look.  Thanks.

**Comment by nihgwu** [comment]
@chetstone test passes now and the slot issue has been solved, sorry for not test it before, i'm going to upgrade the dev deps too and then I think is ready for merge

**Comment by nihgwu** [comment]
@chetstone I upgrade the test snap just because the ListView changes after upgrade react-native, the test snap keeps the same with the former version

**Comment by nihgwu** [comment]
pretty sure it works great with all the test data

**Comment by chetstone** [comment]
Looks good. The refactoring you've done improves the structure and readability of the code. Thanks!
It seems to work the same as before in my app and in the Sortable example. I was hoping it might fix some other problems, like #64, but no such luck. Ah well.

There are a couple of minor issues I have questions about:

1. Regarding your removal of `react-timer-mixin`, you've removed the call to `setTimeout()`, but `requestAnimationFrame()` is still being used. Don't you think the supplied callback could get called after the component is unmounted?

2. There are a couple of warnings now when the `jest` tests are run:
```
    Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

  console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
    Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
```

The React.createClass warning could probably be fixed simply by upgrading `example.js` (the one in the top level) to es6 but I'm not sure where the PropTypes come in. Maybe `react-test-renderer` needs to be upgraded?

3. I notice you've reverted your change of `measureWrapper` to use `runafterinteractions` instead of `onLayout`. I thought that was the fix you made for the problem in your app. Does your app still work with this code? :-)

**Comment by nihgwu** [comment]
quick answers:
1. I didn't look into this part, but I believe it's safe to just leave it there, I always get warnings about changing unmounted components, not all the warnings needs to be handled, but I will try to fix it
2. I didn't changed the code and deps for example, I think the **PropTypes** warning is irrelevant with this PR, so I think we can just ignore it, but I guess the warning is from `react-native` it self as there are **React.PropTypes** in the source code with the version we are using
3. yes, it still works, I use `runAfterInteraction` just because I want to follow your method the measure the layout params, but I find that some of the params are not needed and all the needed params could be got via **onLayout**, and I've explained that measuring layout right in `onLayout` is the best place, so I did that change

So I think this PR is ready for merging right? for #64 , I didn't notice it before and it's still open, so I think is irrelevant to this PR, I'll take a look later

**Comment by chetstone** [comment]
> I didn't look into this part, but I believe it's safe to just leave it there, I always get warnings about changing unmounted components, not all the warnings needs to be handled, but I will try to fix it

Thinking more about it, it doesn't seem like it could harm anything because when the component is remounted it will reinitialize and overwrite any state that might have changed.

Thanks a lot for your perserverance and patience with my delays.

**Comment by antoinerousseau** [comment]
can you publish this on npm please?

**Comment by chetstone** [comment]
@antoinerousseau
 Done

**Comment by nihgwu** [comment]
@chetstone can you add me as a collaborator? I've come with some bug fixes, like #64 and other strange behaviors I've encountered with.
I'm think of addressing them in one PR or splitting them into several PRs

**Comment by chetstone** [comment]
That will be great to have you as a collaborator, but the repository owner, @deanmcpherson, has to do the addition. 

If he doesn't respond, I've been freed up of some other projects so hopefully I can respond more quickly if you want to submit PRs. I would prefer smaller ones.

**Comment by nihgwu** [comment]
@chetstone kindly ping to review my PRs 😄

**Comment by deanmcpherson** [comment]
Het @chetstone @nihgwu, I've added @nihgwu as a collaborator 😄

**Comment by nihgwu** [comment]
@deanmcpherson thanks Dean

**Comment by deanmcpherson** [comment]
You're welcome! Thanks for contributing 👍

**Comment by chetstone** [comment]
I’m taking a look now.

**Pull request merged**
