### PR TITLE
Fix undefined refs crashes

### PR DESCRIPTION
**Pull request by Minishlink**

### CODE REVIEW

**Comment by nihgwu** [comment]
just curious, when will the `refs` is `undefined`, per you another PR, seems you pass a functional component which has no refs itself, but I don't think it would happen with a class component, as you can only access those methods after the component is rendered

**Comment by Minishlink** [comment]
We had a crash on `this.refs.view.measure`.
I took the liberty to add checks for `this.refs.list` too since there were none, it's quite standard to do that for refs btw :)

**Comment by nihgwu** [comment]
But it should be always safe to access refs after component is mounted, curious on how the crash happens

**Comment by Arunkumar-Precise** [comment]
I have same problem when **navigate quickly**, happen this,


1510136584652 jpeg


How can i solve it?

**Comment by nihgwu** [comment]
well it's always be good to be cautious, I'd love to land this, thanks

**Pull request merged**
